name: cdx_comments
description: A Flutter package for managing comments with support for replies, likes, reporting, and user blocking.
version: 0.0.2
homepage: https://github.com/FabrizioBilleciUNICT/cdx_comments
repository: https://github.com/FabrizioBilleciUNICT/cdx_comments

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
