import 'models/comment.dart';
import 'models/comment_config.dart';
import 'models/user_info.dart';
import 'services/comment_service.dart';

/// Controller for managing comment operations.
///
/// This class orchestrates comment-related business logic by delegating
/// to a [CommentService] implementation. It handles comment creation,
/// replies, likes, and deletions.
///
/// Example:
/// ```dart
/// final service = MyCommentService();
/// final config = CommentConfig(badWords: '');
/// final user = UserInfo(uuid: 'user-1', name: 'John Doe');
/// final controller = CommentController(
///   service: service,
///   config: config,
///   user: user,
/// );
/// ```
class CommentController {
  /// The service implementation for comment operations.
  final CommentService service;
  
  /// Configuration for the comments module.
  final CommentConfig config;
  
  /// Information about the current user.
  final UserInfo user;
  
  /// Creates a new [CommentController].
  ///
  /// All parameters are required:
  /// - [service]: The implementation of [CommentService] to use
  /// - [config]: Configuration for the comments module
  /// - [user]: Information about the current user
  CommentController({
    required this.service,
    required this.config,
    required this.user,
  });

  /// Fetches comments for a specific entity.
  ///
  /// Returns a list of root comments (comments without a parent).
  /// Replies are not included in this list; use [getReplies] to fetch them.
  ///
  /// [entityId] is the identifier of the entity (e.g., post, article) 
  /// for which to fetch comments.
  ///
  /// Returns an empty list if no comments are found.
  Future<List<Comment>> fetchComments(String entityId) async {
    return await service.fetchComments(entityId, config, 1);
  }

  /// Posts a new comment for an entity.
  ///
  /// Creates a new comment with the current user's information.
  /// The comment ID will be generated by the service implementation.
  ///
  /// [entityId] is the identifier of the entity to comment on.
  /// [content] is the text content of the comment.
  ///
  /// Returns the created [Comment] if successful, or `null` if the operation failed.
  Future<Comment?> postComment(String entityId, String content) async {
    final comment = Comment(
      id: '',
      date: DateTime.now(),
      content: content,
      entityId: entityId,
      userId: user.uuid,
      username: user.name,
    );
    return await service.postComment(comment, config);
  }

  /// Posts a reply to an existing comment.
  ///
  /// Creates a new comment that is a reply to the specified parent comment.
  /// The reply will be associated with both the parent comment and the entity.
  ///
  /// [entityId] is the identifier of the entity.
  /// [parentCommentId] is the ID of the comment being replied to.
  /// [content] is the text content of the reply.
  ///
  /// Returns the created reply [Comment] if successful, or `null` if the operation failed.
  Future<Comment?> postReply(String entityId, String parentCommentId, String content) async {
    final comment = Comment(
      id: '',
      date: DateTime.now(),
      content: content,
      parentId: parentCommentId,
      entityId: entityId,
      userId: user.uuid,
      username: user.name,
    );
    return await service.postReply(comment);
  }

  /// Toggles the like status of a comment.
  ///
  /// If the comment is currently liked, it will be unliked, and vice versa.
  /// The returned [Comment] will have updated [Comment.isLiked] and [Comment.likeCount] values.
  ///
  /// [commentId] is the ID of the comment to toggle like for.
  ///
  /// Returns the updated [Comment] with new like status, or `null` if the operation failed.
  Future<Comment?> toggleLike(String commentId) async {
    return await service.toggleLikeComment(commentId);
  }

  /// Deletes a comment.
  ///
  /// Permanently removes the comment from the system.
  /// This operation cannot be undone.
  ///
  /// [commentId] is the ID of the comment to delete.
  ///
  /// Throws an exception if the deletion fails.
  Future<void> deleteComment(String commentId) async {
    await service.deleteComment(commentId);
  }

  Future<List<Comment>> getReplies(String commentId, [int page = 1]) async {
    return await service.fetchReplies(commentId, page);
  }
}